# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Liquid Blog"
description: Healthier Democracy

email: info@liquid.us
#blog logo
logo: "/assets/icon-reduced-300.png"
# blog cover
cover: "/assets/statue_of_liberty.jpg"
#blog logo
twitter_large: "/assets/twitter_large.png"

paginate:	30
permalink: pretty # remove .html from post urls

url: "https://blog.liquid.us" # url of the blog
app_url: "https://liquid.us" # link back to the main app
baseurl: ""
#used to display twitter cards
twitter_handle: '@Liquid_US'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/Liquid_US
    desc: Follow us on twitter
    username: "@Liquid_US"
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/voteliquid/
    username: "@VoteLiquid"
    desc: Connect with us on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: envelope
    url:  mailto:info@liquid.us
    desc: Contact us by email
    share_url:
    share_title:
    share_link:

sass:
  sass_dir: css/_sass
