# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The United Blog"
description: Liquid Democracy Is Now Possible.

email: info@united.vote
#blog logo
logo: "/assets/icon-reduced-300.png"
# blog cover
cover: "/assets/america_cover.jpg"

paginate:	30
permalink: pretty # remove .html from post urls

url: "https://blog.united.vote" # url of the blog
app_url: "https://united.vote" # link back to the main app
baseurl: ""
#used to display twitter cards
twitter_handle: '@united_vote'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/united_vote
    desc: Follow us on twitter
    username: "@united_vote"
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/unitedvote/
    username: "@unitedvote"
    desc: Connect with us on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: envelope
    url:  mailto:info@united.vote
    desc: Contact us by email
    share_url:
    share_title:
    share_link:

sass:
  sass_dir: css/_sass
