# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Liquid Blog"
description: Liquid Democracy Is Now Possible.

email: info@liquid.vote
#blog logo
logo: "/assets/images/icon-reduced-300.png"
# blog cover
cover: "/assets/images/america_cover.jpg"

paginate:	30
permalink: pretty # remove .html from post urls

url: "https://blog.liquid.vote" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@liquid_vote'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/liquid_vote
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/liquidvote/
    desc: Connect with us on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: envelope
    url:  mailto:info@liquid.vote
    desc: Contact us by email
    share_url:
    share_title:
    share_link:

sass:
  sass_dir: css/_sass
